name: Gerar APK Gratuito
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Criar pasta www exigida pelo app
        run: |
          mkdir -p www
          cp index.html www/index.html

      - name: Instalar dependencias e Capacitor
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Inicializar Projeto Capacitor
        run: |
          npx cap init "Meu Planner" "com.genilson.meuplanner" --web-dir=www

      - name: Criar e estruturar pasta Android nativa
        run: |
          npx cap add android
          npx cap @capacitor/cli create android
          npx cap sync

      - name: Configurar o Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Compilar o arquivo APK final
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar o arquivo para Download
        uses: actions/upload-artifact@v4
        with:
          name: meu-planner-apk-gratis
          path: android/app/build/outputs/apk/debug/app-debug.apk
